#!/bin/bash
# ---- pak builder
# ---- by tyler burnam


# Ubuntu only

printf "\nr o d e n /\ b u i l d\n\n"

printf "**********************************\n"
printf "Downloading dependencies (step 1/3)"
printf "**********************************\n"

sudo apt-get -y update 
sudo add-apt-repository ppa:nginx/stable
sudo apt-get -y install nginx
sudo apt-get -y install build-essential


printf "**********************************\n"
printf "Building file structure (step 1/3)"
printf "**********************************\n"
mkdir rodenComputeCluster
mkdir rodenComputeCluster/rodenComputeServer
mkdir rodenComputeCluster/rodenComputeLayer


printf "**********************************\n"
printf "Optimizing system (step 3/3)"
printf "**********************************\n"
cd ~
git clone https://gist.github.com/13c713e6082722e0b02d271f061fe8f7.git vimrc
rm ~/.vimrc
cat vimrc/vimrcStarterCpp > ~/.vimrc
rm -rf vimrc
